* Org-mode Resources
- [[https://orgmode.org/orgcard.txt][Cheat Sheet]]
- Org-mode's Emacs menu item
- [[info:org][Manual]]
- [[https://orgmode.org/worg/][Community Wiki (Worg)]]
  - [[https://orgmode.org/worg/org-tutorials/][Tutorials]]
  - [[https://orgmode.org/worg/doc.html][Documentation for hooks, commands, options]]
- [[https://orgmode.org/][Home page]]

* Work Log                                                           :ATTACH:
:PROPERTIES:
:ID:       b4cc1df0-5d8a-41ed-b9d2-f2aac0a34b82
:END:
* An Exercise in (F)utility
** [[file:WSL.org][WSL]]
** [[file:R.org][R]]
SPC m a F over heading opens attached dir in dired
*** Shiny
When the file is copied, where is it stored? Is it better to use a link instead
to an unstructure org directory where all org files live? Also, wouldn't a link
show changes to the original file in real time? I can't edit stashed attachment
files as part of a project. Perhaps this would work better for linking to org
files?  See also spc m f. I think it shows you location if you're hovered over
an attachedfile.
Also M-x orgattachdir and check out the commands that show up.
Also investigate spc m a z for synchronization with attachment dirs. What does
this synchronize?
org-attach-directory
Check out sorce code for org-attach:
http://web.mit.edu/Emacs/source/emacs/lisp/org/org-attach.el
This solution looks interesting:
https://emacs.stackexchange.com/questions/26412/human-readable-directory-tree-with-org-attach
See org-manage and ScriptDevil/org-fstree https://blog.modelworks.ch/using-org-mode-to-keep-track-of-your-project-files/
org-git-link:
https://orgmode.org/worg/org-contrib/org-git-link.html
https://orgmode.org/worg/org-tutorials/org-vcs.html

* Unorganized
** Emacs
If you see (DOS) on left of modeline, run
revert-buffer-with-coding-system, and select utf-8-unix or
something. Save the buffer. Then :%s/\r//.

If you get the metahelp buffer when pressing C-h s, it's because the C- key was
still depressed. E.g. holding the C- key results in C-h C-s. You don't have to
release it. It doesn't seem to involve a timer, but rather a lazy C- finger that
doesn't raise quickly enough.

* Personal
:PROPERTIES:
:ID:       d23b9dbe-dcd0-4c1d-9ab4-ec4f0587af6b
:END:
** DONE Buying a car                                                :ATTACH:
CLOSED: [2020-10-03 Sat 12:06]
:PROPERTIES:
:ID:       054F93AA-2BE0-4357-A894-E9F913A01521
:END:
**
** Civ VI                                                           :ATTACH:
:PROPERTIES:
:ID:       73DAF95E-3E3F-4243-91EB-78205ED3D31E
:END:
** Home cleaning                                                    :ATTACH:
:PROPERTIES:
:ID:       BE936F0A-3F99-42B2-BF03-8C37E4A296F5
:END:
** Voting in Sacramento                                             :ATTACH:
:PROPERTIES:
:ID:       4579B4AE-EE34-4B7B-9F94-F2B4FE770DBE
:END:
** Housing                                                          :ATTACH:
:PROPERTIES:
:ID:       e953aecb-6604-453b-a018-c2c7ffcaf040
:END:
